### ISSUE TITLE
갤러리 리프레시 기능 넣기

### ISSUE THREAD

**Issue by Taewan-P** [Taewan-P/Card_News_Making_Tool#1]
이미지를 편집하고 난 뒤에 갤러리 새로고침을 안해줘서 시스템이 파일이 추가됬는지 안됬는지 인식을 못한다. 그래서 사진을 저장해도 갤러리에 들어가면 편집한 사진이 보이지를 않는다.

**Comment by ptcjw201** [comment]
OK

**Comment by Taewan-P** [comment]
해결완료
